name: HGOAutoKeyboardLayout
main: org.hurricanegames.autokeyboardlayout.AutoKeyboardLayoutPlugin
api-version: 1.13
version: ${version}

website: 'https://github.com/HurricaneGamesOrg/HurricaneGamesOrgAutoKeyboardLayout'
authors:
- _Shevchik_
